package customComponent.gui;


import java.awt.Toolkit;
import java.awt.event.ActionListener;

import javax.swing.JFrame;
import javax.swing.JMenu;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import customComponent.gui.components.ErrorDialogManager;
import customComponent.gui.components.KnowledgeBaseStateObserverMenuItem;
import customComponent.gui.components.NewProjectMenuItem;
import customComponent.gui.components.NewProjectToolBarButton;
import customComponent.gui.components.OpenProjectMenuItem;
import customComponent.gui.components.OpenProjectToolBarButton;
import customComponent.gui.components.adddialog.AddDialogManager;
import customComponent.gui.components.cursor.CursorManager;
import customComponent.gui.components.globalreplace.GlobalReplaceDialogManager;
//import EditDialogManager;
/*import AnalysisViewManager;

import JoinEntitiesDialogManager;*/
import customComponent.gui.components.manager.AffiliationManager;
import customComponent.gui.components.manager.ReportManager;
import customComponent.App;
import customComponent.gui.UndoStack;
import customComponent.gui.commands.task.ShowManagerTask;
import customComponent.model.knowledgebase.KnowledgeBaseException;
import customComponent.project.CurrentProject;

/**
 *
 * @author mjcobo
 */
public class MainFrame extends JFrame {

  /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
/** Creates new form MainFrame */
	private static final Logger logger = LoggerFactory.getLogger(MainFrame.class);
  public MainFrame() {
    
    //setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/images/logoApp.png")));
    logger.info("CheckPost_1");
    initComponents();
    logger.info("CheckPost_2");
    CursorManager.getInstance().init(this);
    AddDialogManager.getInstance().init(this);
   // EditDialogManager.getInstance().init(this);
   /* JoinEntitiesDialogManager.getInstance().init(this);
    MoveToGroupDialogManager.getInstance().init(this);
    WizardManager.getInstance().init(this);
    AnalysisViewManager.getInstance().init(this);*/
    ErrorDialogManager.getInstance().init(this);
   GlobalReplaceDialogManager.getInstance().init(this);
   setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

   // StatisticDialogManager.getInstance().init(this);*/
   loadDatabase();
  }
  
  private void loadDatabase() {
	  try {
		CurrentProject.getInstance().newProject();
	} catch (KnowledgeBaseException e) {
		// TODO Auto-generated catch block
		e.printStackTrace();
	}
  }

  /**
   * Este metodo se encarga de cerrar la apliacion
   */
  private void finish() {

    int returnVal;

    returnVal = JOptionPane.showConfirmDialog(this,
            "Do you want to close the tool?", "Close tool",
            JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);

    if (returnVal == JOptionPane.YES_OPTION) {

      if (CurrentProject.getInstance().isKnowledbaseLoaded()) {

        try {

          CurrentProject.getInstance().close();

        } catch (KnowledgeBaseException e) {

          e.printStackTrace(System.err);
        }
      }

      dispose();
      System.out.println("Finish.");
      System.exit(0);
    }
  }

  /**
   * 
   */
  public void clearMainPanel() {
  
    this.mainPanel.removeAll();
    this.mainPanel.validate();
    this.mainPanel.repaint();
  }
  
  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

	newProjectToolBarButton = new NewProjectToolBarButton();
	openProjectToolBarButton = new OpenProjectToolBarButton();
    toolBarPanel = new JPanel();
    
    mainPanel = new javax.swing.JPanel();
    mainMenuBar = new javax.swing.JMenuBar();
    
    editMenu = new JMenu();
    globalReplaceMenu = new JMenu();
    globalReplaceAffiliationMenuItem = new KnowledgeBaseStateObserverMenuItem();
    knowledgeBaseMenu = new JMenu();
    
    separator3 = new javax.swing.JPopupMenu.Separator();
    affiliationsManagerMenuItem = new KnowledgeBaseStateObserverMenuItem();
    reportManagerMenuItem = new KnowledgeBaseStateObserverMenuItem();
    authorsMenu = new JMenu();
    
    setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
    setTitle("SciMAT 1.1.04");
    setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
    addWindowListener(new java.awt.event.WindowAdapter() {
      public void windowClosing(java.awt.event.WindowEvent evt) {
       // formWindowClosing(evt);
      }
    });

   toolBarPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

    

    newProjectToolBarButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
       // newProjectToolBarButtonActionPerformed(evt);
      }
    });
   // fileToolBar.add(newProjectToolBarButton);

    openProjectToolBarButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
       // openProjectToolBarButtonActionPerformed(evt);
      }
    });
    
    javax.swing.GroupLayout toolBarPanelLayout = new javax.swing.GroupLayout(toolBarPanel);
    toolBarPanel.setLayout(toolBarPanelLayout);
   /* toolBarPanelLayout.setHorizontalGroup(
      toolBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(toolBarPanelLayout.createSequentialGroup()
       // .addComponent(fileToolBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        //.addComponent(editToolBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(815, Short.MAX_VALUE))
    );*/
    toolBarPanelLayout.setVerticalGroup(
      toolBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(toolBarPanelLayout.createSequentialGroup()
        .addGroup(toolBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING))
        //  .addComponent(fileToolBar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
         //.addComponent(editToolBar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addContainerGap())
    );

    mainPanel.setLayout(new javax.swing.BoxLayout(mainPanel, javax.swing.BoxLayout.LINE_AXIS));
    /*  
     */ 
    editMenu.setText("Edit");
    globalReplaceMenu.setText("Global replace");
    globalReplaceAffiliationMenuItem.setText("Affiliation");
    globalReplaceAffiliationMenuItem.addActionListener(new ActionListener() {
    	@Override
      public void actionPerformed(java.awt.event.ActionEvent evt) {
    	  logger.info("I here");
        globalReplaceAffiliationMenuItemActionPerformed(evt);
      }
    });
    globalReplaceMenu.add(globalReplaceAffiliationMenuItem);
/*
   
    
*/
    editMenu.add(globalReplaceMenu);
  // editMenu.add(separator3);

    mainMenuBar.add(editMenu);

    knowledgeBaseMenu.setText("Knowledge base");
    authorsMenu.setText("Authors");

    affiliationsManagerMenuItem.setText("Affiliations manager");
    affiliationsManagerMenuItem.addActionListener(new ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
    	  logger.info("Here");
        affiliationsManagerMenuItemActionPerformed(evt);
      }
    });
    reportManagerMenuItem.setText("Report manager");
    reportManagerMenuItem.addActionListener(new ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
      	  logger.info("Here");
          reportManagerMenuItemActionPerformed(evt);
        }
      });
    authorsMenu.add(reportManagerMenuItem);
    authorsMenu.add(affiliationsManagerMenuItem);

    knowledgeBaseMenu.add(authorsMenu);
/*
    
*/
    mainMenuBar.add(knowledgeBaseMenu);
/*
    
    
*/
    setJMenuBar(mainMenuBar);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      //.addComponent(toolBarPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
      .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 959, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        //.addComponent(toolBarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 537, Short.MAX_VALUE))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
	    finish();
	  }//GEN-LAST:event_exitMenuItemActionPerformed
  private void reportManagerMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_affiliationsManagerMenuItemActionPerformed
	  logger.info("globalReplaceReportMenuItemActionPerformed");
    (new ShowManagerTask(this.mainPanel, this.reportManger)).execute();
  }//GEN-LAST:event_affiliationsManagerMenuItemActionPerformed
  private void affiliationsManagerMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_affiliationsManagerMenuItemActionPerformed
	  logger.info("globalReplaceAffiliationMenuItemActionPerformed");
    (new ShowManagerTask(this.mainPanel, this.affiliationManger)).execute();
  }//GEN-LAST:event_affiliationsManagerMenuItemActionPerformed

  private void globalReplaceAffiliationMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_globalReplaceAffiliationMenuItemActionPerformed
	  	logger.info("globalReplaceAffiliationMenuItemActionPerformed");
	    GlobalReplaceDialogManager.getInstance().showGlobalAffiliationGlobalReplaceDialog();
	  }//GEN-

  private void globalReplaceReportMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_globalReplaceAffiliationMenuItemActionPerformed
	  	logger.info("globalReplaceAffiliationMenuItemActionPerformed");
	    GlobalReplaceDialogManager.getInstance().showGlobalReportGlobalReplaceDialog();
	  }//GEN-


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private JMenu journalsMenu;
  private javax.swing.JMenu knowledgeBaseMenu;
  private javax.swing.JMenuItem loadAnalysisMenuItem;
  private javax.swing.JMenuBar mainMenuBar;
  private javax.swing.JPanel mainPanel;
  private javax.swing.JMenu exportMenu;
  private javax.swing.JMenu fileMenu;
  private javax.swing.JToolBar fileToolBar;
  private KnowledgeBaseStateObserverMenuItem makeAnalysisMenuItem;
  private NewProjectMenuItem newProjectMenuItem;
  private NewProjectToolBarButton newProjectToolBarButton;
  private OpenProjectMenuItem openProjectMenuItem;
  private OpenProjectToolBarButton openProjectToolBarButton;
  private KnowledgeBaseStateObserverMenuItem globalReplaceAffiliationMenuItem;
  private KnowledgeBaseStateObserverMenuItem affiliationsManagerMenuItem;
  private KnowledgeBaseStateObserverMenuItem reportManagerMenuItem;
 
  private javax.swing.JMenu authorsMenu;
  
  private JMenu editMenu;
 
  private javax.swing.JMenu globalReplaceMenu;
 
  private javax.swing.JPopupMenu.Separator separator1;
  private javax.swing.JPopupMenu.Separator separator2;
  private javax.swing.JPopupMenu.Separator separator3;
  
  private javax.swing.JPanel toolBarPanel;
  
  private javax.swing.JMenu wordsMenu;
  // End of variables declaration//GEN-END:variables
  private final AffiliationManager affiliationManger = new AffiliationManager();
  private final ReportManager reportManger = new ReportManager();
   // private final AboutDialog aboutDialog = new AboutDialog(this);
}
